### ISSUE TITLE
Create snapshots and backups

### ISSUE THREAD

**Issue by KrisLowet** [ansible-collections/hetzner.hcloud#227] opened 2023-06-20 09:23 UTC
##### SUMMARY
Adding the option to create snapshots and backups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[hcloud_server module](https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_module.html#ansible-collections-hetzner-hcloud-hcloud-server-module)

##### ADDITIONAL INFORMATION
Before installing software updates, I like to take a snapshot or a backup from the servers. It would be a great addition to be able to take snapshots or a backup with this module.

**Comment by jooola** [comment] 2023-06-20 10:15
This is probably related to #85

**Comment by jooola** [comment] 2023-07-05 09:52
Closing this as duplicate of #85

**Closed by jooola** 2023-07-05 09:52 UTC
